export enum InjectionToken {
    USER_SESSION_CACHE_REPOSITORY = "USER_SESSION_CACHE_REPOSITORY",
    USER_SESSION_REPOSITORY = "USER_SESSION_REPOSITORY",
    JWT_TOKEN_SERVICE = "JWT_TOKEN_SERVICE",
    TOKEN_SERVICE = "TOKEN_SERVICE",
    USER_SESSION_PERSISTANCE_SERVICE = "USER_SESSION_PERSISTANCE_SERVICE"
}