export enum InjectionToken {
    USER_SESSION_CACHE_REPOSITORY = "USER_SESSION_CACHE_REPOSITORY",
    USER_SESSION_REPOSITORY = "USER_SESSION_REPOSITORY",
    JWT_TOKEN_SERVICE = "JWT_TOKEN_SERVICE"
}