// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: protos/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface TokenPair {
  refreshToken: string;
  accessToken: string;
}

export interface UserData {
  userId: string;
}

export interface TokenRequest {
  token: string;
}

export interface DeviceInfo {
  device: string;
  location: string;
  ipAddress: string;
}

export interface UserDataWithDeviceRequest {
  userData: UserData | undefined;
  deviceInfo: DeviceInfo | undefined;
}

export interface TokensAndDataRequest {
  data: UserDataWithDeviceRequest | undefined;
  tokens: TokenPair | undefined;
}

/** RESPONSE !!! */
export interface Error {
  errorMessage: string;
  statusCode: number;
}

export interface UserAndTokensResponse {
  userData: UserData | undefined;
  tokenPair: TokenPair | undefined;
}

export interface SuccessResponse {
  success: boolean;
  error?: Error | undefined;
}

export interface CreateUserSessionResponse {
  success: boolean;
  data?: UserAndTokensResponse | undefined;
  error?: Error | undefined;
}

export interface RefreshTokensResponse {
  success: boolean;
  data?: TokenPair | undefined;
  error?: Error | undefined;
}

export interface AuthServiceClient {
  authenticate(request: TokensAndDataRequest): Observable<SuccessResponse>;

  createUserSession(request: UserDataWithDeviceRequest): Observable<CreateUserSessionResponse>;

  refreshTokens(request: TokensAndDataRequest): Observable<RefreshTokensResponse>;
}

export interface AuthServiceController {
  authenticate(request: TokensAndDataRequest): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;

  createUserSession(
    request: UserDataWithDeviceRequest,
  ): Promise<CreateUserSessionResponse> | Observable<CreateUserSessionResponse> | CreateUserSessionResponse;

  refreshTokens(
    request: TokensAndDataRequest,
  ): Promise<RefreshTokensResponse> | Observable<RefreshTokensResponse> | RefreshTokensResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["authenticate", "createUserSession", "refreshTokens"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
