// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.32.0
// source: protos/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface UserData {
  userId: string;
}

export interface AuthenticateRequest {
  token: string;
}

export interface DeviceInfo {
  device: string;
  location: string;
  ipAddress: string;
}

export interface CreateUserRequest {
  userData: UserData | undefined;
  deviceInfo: DeviceInfo | undefined;
}

export interface SuccessResponse {
  success: boolean;
}

export interface TokenPair {
  refreshToken: string;
  accessToken: string;
}

export interface User {
  success: SuccessResponse | undefined;
  userData: UserData | undefined;
  tokenPair: TokenPair | undefined;
}

export interface AuthServiceClient {
  authenticate(request: AuthenticateRequest): Observable<SuccessResponse>;

  createUserSession(request: CreateUserRequest): Observable<User>;
}

export interface AuthServiceController {
  authenticate(request: AuthenticateRequest): Promise<SuccessResponse> | Observable<SuccessResponse> | SuccessResponse;

  createUserSession(request: CreateUserRequest): Promise<User> | Observable<User> | User;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["authenticate", "createUserSession"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
