export enum InjectionToken {
  USER_DRIVER_DAO = 'USER_DRIVER_DAO',
  USER_CLIENT_DAO = 'USER_CLIENT_DAO',
  USER_DRIVER_REPOSITORY = 'USER_DRIVER_REPOSITORY',
  USER_CLIENT_REPOSITORY = 'USER_CLIENT_REPOSITORY',
  USER_DRIVER_SERVICE = 'USER_DRIVER_SERVICE',
  USER_CLIENT_SERVICE = 'USER_CLIENT_SERVICE',
  USER_DRIVER_REDIS_DAO = 'USER_DRIVER_REDIS_DAO',
  USER_CLIENT_REDIS_DAO = 'USER_CLIENT_REDIS_DAO',

  AUTH_DRIVER_DAO = 'AUTH_DRIVER_DAO',
  AUTH_CLIENT_DAO = 'AUTH_CLIENT_DAO',
  AUTH_DRIVER_REPOSITORY = 'AUTH_DRIVER_REPOSITORY',
  AUTH_CLIENT_REPOSITORY = 'AUTH_CLIENT_REPOSITORY',
  AUTH_DRIVER_SERVICE = 'AUTH_DRIVER_SERVICE',
  AUTH_CLIENT_SERVICE = 'AUTH_CLIENT_SERVICE',
  AUTH_DRIVER_REDIS_DAO = 'AUTH_DRIVER_REDIS_DAO',
  AUTH_CLIENT_REDIS_DAO = 'AUTH_CLIENT_REDIS_DAO',
}
