syntax = "proto3";

package auth;

service AuthService {
    rpc Authenticate(TokensAndDataRequest) returns (SuccessResponse);
    rpc CreateUserSession(UserDataWithDeviceRequest) returns (CreateUserSessionResponse);
    rpc RefreshTokens(TokensAndDataRequest) returns (RefreshTokensResponse);
}




// SHARED !!!

message TokenPair {
    string refreshToken = 1;
    string accessToken = 2;
}

message UserData {
    string userId = 1;
}

// REQUEST !!!

message TokenRequest {
    string token = 1;
}

message DeviceInfo {
  string device = 1;
  string location = 2;
  string ipAddress = 3;
}

message UserDataWithDeviceRequest {
    UserData userData = 1;
    DeviceInfo deviceInfo = 2;
}

message TokensAndDataRequest {
    UserDataWithDeviceRequest data = 1;
    TokenPair tokens = 2;
}

// RESPONSE !!!
message Error {
    string errorMessage = 1;
    int32 statusCode = 2;
}
message UserAndTokensResponse {
    UserData userData = 1;
    TokenPair tokenPair = 2;
}



message SuccessResponse {
    bool success = 1;
    optional Error error = 2;
}

message CreateUserSessionResponse {
    bool success = 1;
    oneof result {
        UserAndTokensResponse data = 2;
        Error error = 3;
    }
}

message RefreshTokensResponse {
    bool success = 1;
    oneof result {
        TokenPair data = 2;
        Error error = 3;
    }
}