syntax = "proto3";

package auth;

service AuthService {
    rpc Authenticate(AuthenticateRequest) returns (SuccessResponse);
    rpc CreateUserSession(CreateUserRequest) returns (CreateUserSessionResponse);
    rpc RefreshTokens(RefreshTokenRequest) returns (TokenPair);
}

// SHARED !!!

message UserData {
    string userId = 1;
}

// REQUEST !!!

message AuthenticateRequest {
    string token = 1;
}

message DeviceInfo {
  string device = 1;
  string location = 2;
  string ipAddress = 3;
}

message CreateUserRequest {
    UserData userData = 1;
    DeviceInfo deviceInfo = 2;
}

// RESPONSE !!!

message SuccessResponse {
    bool success = 1;
}

message Error {
    string errorMessage = 1;
    int32 statusCode = 2;
}

message TokenPair {
    string refreshToken = 1;
    string accessToken = 2;
}

message User {
    UserData userData = 1;
    TokenPair tokenPair = 2;
}

message CreateUserSessionResponse {
    bool success = 1;
    oneof result {
        User user = 2;
        Error error = 3;
    }
}

message RefreshTokenRequest {
    UserData userData = 1;
    DeviceInfo deviceInfo = 2;
    TokenPair tokens = 3;
}