export enum NestjsInjectionToken {
    REQUEST_STORAGE = 'REQUEST_STORAGE',
    REQUEST_STORAGE_MIDDLEWARE = 'REQUEST_STORAGE_MIDDLEWARE',
    MODULE_REF_STORE = 'MODULE_REF_STORE',
    MODULE_REF_STORE_MIDDLEWARE = 'MODULE_REF_STORE_MIDDLEWARE',
    MODULE_REF = 'MODULE_REF',
    TRANSACTION_MANAGER_SERVICE = 'TRANSACTION_MANAGER_SERVICE',
    CATCH_FILTER = 'CATCH_FILTER',
    GRPC_CATCH_FILTER = "GRPC_CATCH_FILTER",
    COMMAND_CONTEXT_INTERCEPTOR = 'COMMAND_CONTEXT_INTERCEPTOR',
    TRANSACTIONAL_INTERCEPTOR = 'TRANSACTIONAL_INTERCEPTOR',
    ADD_SUCCESS_FIELD_INTERCEPTOR = 'ADD_SUCCESS_FIELD_INTERCEPTOR',
    QUERY_RUNNER_MANAGER = "QUERY_RUNNER_MANAGER",
}